FROM ubuntu:xenial

# Setup www dir
WORKDIR /var/www
RUN chown www-data:www-data /var/www
USER www-data

#Start installing dashboard 
RUN git clone https://github.com/xyrodileas/misp-dashboard.git
WORKDIR /var/www/misp-dashboard
RUN ./install_dependencies.sh

#Configure misp-dashboard

#Run misp-dashboard
RUN . ./DASHENV/bin/activate
RUN ./zmq_subscriber.py &
RUN ./zmq_dispatcher.py &
RUN ./server.py
